Create RegisterAddonRouter.php
anomalylabs/streams-platform pull request #546
Opened 2018-03-27 00:51 UTC by olivia-outshine

2018-03-27 01:12 UTC, Piterden requested changes

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +	public function __countruct(array $routes, Addon $addon, string $namespace = '')
Typo

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +		foreach ( $this->routes as $uri => $route ) {
You should follow codestyle.
```php
foreach ($this->routes as $uri => $route) {

}
```

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +			if ( ! is_array($route) )
Here is the same like above
```php
if (!is_array($route))
```

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +			$verb = Arr::pull($route, 'verb', 'any');
Try [this](https://laravel.com/docs/5.5/helpers#method-array-pull) instead of injecting `Arr`!

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +			Arr::set($route, 'streams::addon', $this->addon->getNamespace());
`array_set()` is much slower than native!!!

2018-03-27 01:12 UTC, Piterden commented on src/Addon/Command/RegisterAddonRouter.php
> +				$route = $router->{$verb}($uri, $route)->where($constraints);
I believe, `call_user_func*` is more reliable...

2018-05-03 17:25 UTC, RyanThompson commented
Not sure where to start this one and super conflicted for a while now. Closing - perhaps open a discussion up in slack / here / the forum on this PRs intentions.

2018-05-03 17:25 UTC, closed without merging