namespaces on assignments where not respected by migrator
anomalylabs/streams-platform pull request #578
Opened 2018-06-07 12:17 UTC by beije

Fixes issue where namespaces on assignments where not respected by the migrator

2018-06-07 12:22 UTC, Piterden requested changes

2018-06-07 12:22 UTC, Piterden commented on src/Database/Migration/Assignment/AssignmentMigrator.php
> +            $namespace = (isset($assignment['namespace']) ? $assignment['namespace'] : $stream->getNamespace());
```php
$namespace = array_get($assignment, 'namespace', $stream->getNamespace());
```
We are inside Laravel, bro... ))

2018-06-07 12:22 UTC, Piterden commented on src/Database/Migration/Assignment/AssignmentMigrator.php
> +            unset($assignment['namespace']);
```php
array_forget($assignment, 'namespace');
```
It is not necessary, but we are inside Laravel...

2018-06-07 12:35 UTC, beije commented
@Piterden thanks, I've implemented the changes :)

2018-06-07 19:40 UTC, Piterden commented
@RyanThompson congrats about 100th star!! )))

2018-06-07 20:07 UTC, beije commented
@Piterden No, I don't have a gitlab account(?) :)

2018-06-08 11:39 UTC, RyanThompson commented
Nicely done! Thank you.

2018-06-08 11:40 UTC, merged